### ISSUE TITLE
whitelist also for team ids

### ISSUE THREAD

**Issue by runningman84** [luizfonseca/traefik-github-oauth-plugin#18]
This plugin looks great, I would also like to whitelist team ids in addition to userids or usernames.

Furthermore it would be great to also force mfa.

We did a similar thing with the external auth project:
https://github.com/travisghansen/external-auth-server/blob/c3337e05ebc581dc5e79d31b9d844076439ecc85/contrib/generate-config-helm-traefik-github.js#L127

**Comment by luizfonseca** [comment]
Hey @runningman84, that's a great idea. I've prepared a small PR that adds team support here: https://github.com/luizfonseca/traefik-github-oauth-plugin/pull/21


Now, in regards to MFA I have to investigate further but seems doable. I might also restructure the codebase a bit to allow for even more filters (though `external-auth-server` seems like the perfect endgame to me...).

That said, if you are willing; I'm open to any contributions if you feel they would be valuable to the repo!

--

_P.S.: Although I'm confident that it's working as expected, I will dedicate some time to write some tests/extensively test the PR on a Traefik setup in the following days._

**Comment by runningman84** [comment]
Looking forwar to a release, the pr looks good from my point of view. I think it is already okay for my usecase only the force mfa flag is missing so far.

**Comment by luizfonseca** [comment]
@runningman84 Released on the `0.4.0` version (important to update both the sidecar and the plugin)

I will address the MFA in a follow up PR.

**Comment by autarchprinceps** [comment]
Hmm, gave it a quick test. I don't think public data will be sufficient to know a users team memberships. You'd need to request organization read access for that.
<img width="706" alt="image" src="https://github.com/user-attachments/assets/8bf974fc-6e86-4fe2-b601-0a28432dd502" />

**Comment by luizfonseca** [comment]
@autarchprinceps Good point! re: the doc > https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#list-teams-for-the-authenticated-user

So `user`, `repo` or `read:org` scopes attached to your oauth credentials are required. 

I will add this to the README just in case. 👍🏽

**Comment by luizfonseca** [comment]
Added to the README: https://github.com/luizfonseca/traefik-github-oauth-plugin?tab=readme-ov-file#oauth-configuration

**Comment by luizfonseca** [comment]
@runningman84 re `MFA` -- would you imagine the configuration to be akin to this? 


```yaml
# Requires that all users have `two_factor_authentication` set to `true` via the Github API
mfa_required: true

whitelist:
  logins:
    - luizfonseca
```

A possibility here is to also specify which users you want MFA enabled, e.g.

```yaml
whitelist:
  mfa_required:
    - luizfonseca
    - runningman84
```

**Comment by runningman84** [comment]
I think a global mfa_required is the right thing... the list of users or teams might be long, I want to just setup that globally.

**Comment by autarchprinceps** [comment]
> @autarchprinceps Good point! re: the doc > https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#list-teams-for-the-authenticated-user
> 
> So `user`, `repo` or `read:org` scopes attached to your oauth credentials are required.
> 
> I will add this to the README just in case. 👍🏽

Hmm, I think we are missunderstanding each other. This is not something you as the user can setup in each GitHub Oauth App, but the actual GitHub Request page your software generates has to be different. That's certainly how it was for other GitHub Oauth Plugins. The actual page generated by the auth layer then includes your organisations and you can authenticate for each you need:
![image](https://github.com/user-attachments/assets/5a43667b-9e25-45c0-bb3a-0af7d1a58bfc)
vs just the public access you see above.

Github Oauth App just contains the settings for the callback URLs and device flow, no settings in regards to scope:
![image](https://github.com/user-attachments/assets/a34d3bb7-eba0-48bc-816c-7c772de86e55)

**Comment by luizfonseca** [comment]
@autarchprinceps Ah yes, sorry you are right - I was thinking about personal tokens for some reason.


I was thinking more towards this bit: https://github.com/luizfonseca/traefik-github-oauth-plugin/pull/38

IE, for `teams` to work one might need to request an additional scope which wasn't possible before.

**Comment by autarchprinceps** [comment]
Hmm, that makes the login look like I expected, yes. But after logging in successful I get an internal server error now, and traefik logs:
```
service=traefik-github-oauth-middleware level=debug msg=Failed to get user from cookie: http: named cookie not present
GET / HTTP/2.0" 0 0 "-" "-" "mytestingress"
```

**Comment by luizfonseca** [comment]
@autarchprinceps hm, interesting. could you double check 2 things for me?

- was there a cookie present when you called the particular endpoint?
- if yes, when you parse it via `jwt.io`, do you see `teams: []` or any other value?

I'd also look if with/without the cookie being present initially, the requests work as expected.

**Comment by luizfonseca** [comment]
@autarchprinceps in any case, I found a possible edge case when previous tokens would fail since they are missing the `teams` key we add on every token: https://github.com/luizfonseca/traefik-github-oauth-plugin/pull/40 -- should be up in v`0.4.2` just in case.

**Comment by luizfonseca** [comment]
@runningman84 Added support to check for the 2FA status from Github: `0.5.0` (update both server and the middleware for this to work)
PR > #42

**Comment by autarchprinceps** [comment]
Ok, I retested it with 0.5.0 and with cleared cookies as well as incognito mode and a browser I have never used for this before. The cookie has "teams": null, even after a complete relogin and reapproval from Github. The app did ask and I gave it  "Read org and team membership, read org projects", as well as again access specifically being approved to the organisation under organisational access.

**Comment by luizfonseca** [comment]
Ok! Thanks for report -- I will debug this further today to see if I missed something in regards to the check (seems that the request might be failing on the go side of things).

**Comment by autarchprinceps** [comment]
Setting everything I can find to debug, I additionally see these messages in the logs coming from traefik itself, instead of the oauth pod. In the oauth pod itself there is still only an info level log for the access, and the request never gets to the basic hello-world page pod I put as the actual backend behind the authentication for test purposes.
```
"GET / HTTP/1.1" 404 19 "-" "-" 840275 "default-oauth-test-oauth-test-redacted@kubernetes" "http://redacted:80" 3ms
{"plugin":"plugin-github-oauth","module":"github.com/luizfonseca/traefik-github-oauth-plugin","runtime":"","time":"2025-01-06T10:22:06Z","level":"error","message":"plugins-storage/sources/gop-2108516520/src/github.com/luizfonseca/traefik-github-oauth-plugin/internal/pkg/jwt/jwt.go:25:16: panic: github.com/luizfonseca/traefik-github-oauth-plugin/internal/pkg/jwt.ParseTokenString(...)"}
{"plugin":"plugin-github-oauth","module":"github.com/luizfonseca/traefik-github-oauth-plugin","runtime":"","time":"2025-01-06T10:22:06Z","level":"error","message":"plugins-storage/sources/gop-2108516520/src/github.com/luizfonseca/traefik-github-oauth-plugin/middleware_plugin.go:264:20: panic: github.com/luizfonseca/traefik-github-oauth-plugin.getGitHubUserFromCookie(...)"}
{"plugin":"plugin-github-oauth","module":"github.com/luizfonseca/traefik-github-oauth-plugin","runtime":"","time":"2025-01-06T10:22:06Z","level":"error","message":"plugins-storage/sources/gop-2108516520/src/github.com/luizfonseca/traefik-github-oauth-plugin/middleware_plugin.go:125:15: panic: github.com/luizfonseca/traefik-github-oauth-plugin.handleRequest(...)"}
{"plugin":"plugin-github-oauth","module":"github.com/luizfonseca/traefik-github-oauth-plugin","runtime":"","time":"2025-01-06T10:22:06Z","level":"error","message":"plugins-storage/sources/gop-2108516520/src/github.com/luizfonseca/traefik-github-oauth-plugin/middleware_plugin.go:114:5: panic: github.com/luizfonseca/traefik-github-oauth-plugin.ServeHTTP(...)"}
"GET / HTTP/2.0" 0 0 "-" "-" 2649726 "default-hello-world-hello-world-redacted@kubernetes" "-" 1ms
{"level":"error","middlewareName":"traefik-internal-recovery","middlewareType":"Recovery","time":"2025-01-06T10:22:06Z","message":"Recovered from panic in HTTP handler [redacted - /]: plugins-storage/sources/gop-2108516520/src/github.com/luizfonseca/traefik-github-oauth-plugin/internal/pkg/jwt/jwt.go:35:21: interface conversion: interface {} is nil, not []interface {}"}
{"plugin":"plugin-github-oauth","module":"github.com/luizfonseca/traefik-github-oauth-plugin","runtime":"","time":"2025-01-06T10:22:06Z","level":"error","message":"plugins-storage/sources/gop-2108516520/src/github.com/luizfonseca/traefik-github-oauth-plugin/internal/pkg/jwt/jwt.go:25:16: panic: github.com/luizfonseca/traefik-github-oauth-plugin/internal/pkg/jwt.ParseTokenString(...)"}
{"plugin":"plugin-github-oauth","module":"github.com/luizfonseca/traefik-github-oauth-plugin","runtime":"","time":"2025-01-06T10:22:06Z","level":"error","message":"plugins-storage/sources/gop-2108516520/src/github.com/luizfonseca/traefik-github-oauth-plugin/middleware_plugin.go:264:20: panic: github.com/luizfonseca/traefik-github-oauth-plugin.getGitHubUserFromCookie(...)"}
{"plugin":"plugin-github-oauth","module":"github.com/luizfonseca/traefik-github-oauth-plugin","runtime":"","time":"2025-01-06T10:22:06Z","level":"error","message":"plugins-storage/sources/gop-2108516520/src/github.com/luizfonseca/traefik-github-oauth-plugin/middleware_plugin.go:125:15: panic: github.com/luizfonseca/traefik-github-oauth-plugin.handleRequest(...)"}
{"plugin":"plugin-github-oauth","module":"github.com/luizfonseca/traefik-github-oauth-plugin","runtime":"","time":"2025-01-06T10:22:06Z","level":"error","message":"plugins-storage/sources/gop-2108516520/src/github.com/luizfonseca/traefik-github-oauth-plugin/middleware_plugin.go:114:5: panic: github.com/luizfonseca/traefik-github-oauth-plugin.ServeHTTP(...)"}
```

In terms of ordering:
```
service=traefik-github-oauth-middleware level=debug msg=Failed to get user from cookie: http: named cookie not present
"GET / HTTP/2.0" 401 1 "-" "-" 2647509 "default-hello-world-hello-world-redacted@kubernetes" "-" 37ms
"GET /oauth/redirect?rid=redacted&code=redacted HTTP/2.0" 302 98 "-" "-" 2648004 "default-oauth-test-oauth-test-redacted@kubernetes" "http://redacted:80" 473ms
"GET /_auth?rid=redacted HTTP/2.0" 302 0 "-" "-" 2648008 "default-hello-world-hello-world-redacted" "-" 3ms
```
comes first once (in the new browser session I didn't log into to), which is mirrored in the browser by the expected GitHub Login and GitHub app authorization pages. Then the above mentioned errors appear alongside the URL of the target service, but with the Internal Server Error output, that is definitively not from the target service.
Hope that helps, but if I can provide anything else, feel free to ask.

**Comment by runningman84** [comment]
Is there anything like additional logs which would help you to address this issue @luizfonseca ?

**Comment by luizfonseca** [comment]
Hey @runningman84 & @autarchprinceps, sorry the delay. Got a bit busy in the last few days and had to debug a bit  more slowly.
I've found the following issues (which are now addressed on `v0.5.1`)

- The code was checking for the incorrect teams list, fixed with the proper check and we can now get the proper teams information (requires the app to have the right permissions/scopes akin to `read:org`)

- <img width="271" alt="Screenshot 2025-01-15 at 19 14 47" src="https://github.com/user-attachments/assets/166b1cfd-dafa-4f6e-b22c-a48896c7c848" />


- `interface conversion: interface {} is nil, not []interface {}` is probably the fix I issued for 0.5.0 -- could you confirm that the middleware is the latest as well? Just so I can properly look into it.


- It seems that Github deprecated the property that allows me to check for 2FA -- we can only get that information from an organization endpoint AND as an admin of the org via GRAPHQL (method is gone from recent versions of the sdk that this project uses https://github.com/google/go-github). I will remove the 2FA from the token for now since it's not reflecting actual data sadly. 
- <img width="522" alt="Screenshot 2025-01-15 at 20 35 22" src="https://github.com/user-attachments/assets/1f5a8960-1af5-4c96-84b6-413a3cf7550e" />

- For the 2FA check to work it basically means we would need some sort of admin token attached to it. Luckily an org can enforce 2FA so at least that should be mostly enough?

**Comment by luizfonseca** [comment]
I also added a debug of the current user trying to authenticated in case you want to check if we are getting the right information from the API (the oauth pod should have the `LOG_LEVEL=debug` env variable

**Comment by runningman84** [comment]
You are right the force mfa can also be done on the org level, we will test the updated version.

**Comment by autarchprinceps** [comment]
Yes, 0.5.1 seems to have done the trick. I can certainly get through with team to a hello world pod.

In terms of middleware, we had something like this:
```yaml
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-test
  namespace: default
spec:
  plugin:
    github-oauth:
      apiBaseUrl: https://oauth-test.redacted
      logLevel: debug
      whitelist:
        teams:
        - redacted
```
Of course with the appropriate ingresses and services, traefik plugin installation and a deployment of your image
I think service & ingress are clear enough, but otherwise if it helps somebody:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  values:
    experimental:
      plugins:
        github-oauth:
          moduleName: "github.com/luizfonseca/traefik-github-oauth-plugin"
          version: "v0.5.1"
```
is all we needed to add to the typical traefik ingress controller settings and for the deployment:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth-test
  template:
    metadata:
      labels:
        app: oauth-test
    spec:
      containers:
      - name: oauth-test
        image: luizfonseca/traefik-github-oauth-server:0.5.1
        ports:
        - containerPort: 80
        env:
        - name: GITHUB_OAUTH_CLIENT_ID
          value: redacted
        - name: GITHUB_OAUTH_CLIENT_SECRET
          value: redacted
        - name: API_BASE_URL
          value: https://oauth-test.redacted
        - name: LOG_LEVEL
          value: debug
        - name: GITHUB_OAUTH_SCOPES
          value: read:org
        resources:
          requests:
            cpu: 10m
            memory: 1Gi
          limits:
            memory: 4Gi
```
As for the resources I'm not sure if you have any typical expectations, otherwise we'll do some real world tests to get closer to reality, this was just so I could test.

Other than that, thanks for the support and I would say we can close this with success then.
