### ISSUE TITLE
OAuth in front of service without any auth

### ISSUE THREAD

**Issue by ElliotThiebaut** [luizfonseca/traefik-github-oauth-plugin#51]
I'm trying to use the traefik-github-oauth-plugin to protect routes where the service behind does not have any auth.

For exemple, we have redis insight self hosted that does not support github-oauth and the dashboard exposed at redis-insight.mydomain.com is accessible to anyone.
My plan was to have the traefik-github-oauth-plugin in front so that when a user goes to redis-insight.mydomain.com it asks him to login with Github, and if the user is on the whitelist defined for this service, we is allowed access to redis-insight.mydomain.com otherwide he gets an error. I do not want users inside redis, just protect the access to the route.

I managed to make this work until the final redirect part, where when setting the authPath in the redis insight service config to `/` I get a redirection loop, even if the cookie is already set and passed in the request. I do not want to redirect to something like `/_auth` as there is no user management, and if the user is confirmed as part of the whitelist by the traefik-github-oauth middleware I just want the user to get access to the route.

I don't use any dynamic config file (for now at least), I just put the command for the static config int he service definition and the labels for the dynamic config in the other service definitions. I don't think that's an issue but I may be wrong!

I think it's just me misunderstanding something about how the middleware works and/or a bad config on my part, but I can't seem to figure it out myself!

Here is my current config :

- Traefik service
```yml
services:
  traefik:
    image: "traefik:latest"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --providers.swarm=true
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.exposedbydefault=false
      - --providers.swarm.network=#######
      - --api.insecure=false
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=ERROR
      - --certificatesresolvers.leresolver.acme.httpchallenge=true
      - --certificatesresolvers.leresolver.acme.email=#######
      - --certificatesresolvers.leresolver.acme.storage=/acme/acme.json
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
      - --experimental.plugins.traefik-github-oauth-plugin.modulename=github.com/luizfonseca/traefik-github-oauth-plugin
      - --experimental.plugins.traefik-github-oauth-plugin.version=v0.6.0
    ports:
      - "80:80"
      - "443:443"
    networks:
      - #######
    volumes:
      - #######
      - #######"
    deploy:
      placement:
        constraints: #######
      labels:
        #######
```
- Traefik Github Oauth Server service
```yml
services:
  github-oauth:
    image: "luizfonseca/traefik-github-oauth-server:0.6.0"
    networks:
      - ####### (the same as the traefik network)
    secrets:
      - my-github-oauth-secret  

    environment:
      GITHUB_OAUTH_CLIENT_SECRET_FILE: "/run/secrets/my-github-oauth-secret"
      GITHUB_OAUTH_CLIENT_ID: #######
      GITHUB_OAUTH_SCOPES: "read:org"
      API_BASE_URL: "https://traefik-oauth.medrunner.dev"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik-oauth.rule=Host(`traefik-oauth.mydomain.com`)"
        - "traefik.http.routers.traefik-oauth.entrypoints=websecure"
        - "traefik.http.services.traefik-oauth.loadbalancer.server.port=80"
        - "traefik.http.routers.traefik-oauth.service=traefik-oauth"
        - "traefik.http.routers.traefik-oauth.tls.certresolver=leresolver"

networks:
  public:
    external: true

secrets:
  my-github-oauth-secret:
    external: true
    
```
- Redis Insight service
```yml
services:
  resisinsight:
    image: redis/redisinsight
    volumes:
      - #######
    networks:
      - #######
      - ####### (the same as the traefik network)
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.redisinsight-github-oauth.plugin.traefik-github-oauth-plugin.apiBaseUrl=https://traefik-oauth.mydomain.com"
        - "traefik.http.middlewares.redisinsight-github-oauth.plugin.traefik-github-oauth-plugin.authPath=/"
        - "traefik.http.routers.redisinsight.middlewares=redisinsight-github-oauth"
        - "traefik.http.routers.redisinsight.rule=Host(`redis.mydomain.com`)"
        - "traefik.http.routers.redisinsight.entrypoints=websecure"
        - "traefik.http.services.redisinsight.loadbalancer.server.port=5540"
        - "traefik.http.routers.redisinsight.service=redisinsight"
        - "traefik.http.routers.redisinsight.tls.certresolver=leresolver"
        
networks:
  #######:
    external: true
  #######:
    external: true

volumes:
  #######
```
